// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using content;

namespace content.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190402144713_AddedModelsAndControllers")]
    partial class AddedModelsAndControllers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("capstone_client.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<bool>("IsMoving");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.Property<int?>("RosterId");

                    b.Property<int>("YearsPlayed");

                    b.HasKey("Id");

                    b.HasIndex("RosterId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("capstone_client.Models.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCustom");

                    b.Property<string>("Name");

                    b.Property<int>("ProjectedWins");

                    b.Property<int?>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("capstone_client.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string[]>("Division");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<int[]>("PrimaryColor");

                    b.Property<int[]>("SecondaryColor");

                    b.Property<int[]>("TertiaryColor");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("capstone_client.Models.Player", b =>
                {
                    b.HasOne("capstone_client.Models.Roster", "Roster")
                        .WithMany("Players")
                        .HasForeignKey("RosterId");
                });

            modelBuilder.Entity("capstone_client.Models.Roster", b =>
                {
                    b.HasOne("capstone_client.Models.Team", "Team")
                        .WithMany("Rosters")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
